export const adminConstants = {
  UPDATE_REQUEST: 'ADMINS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'ADMINS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'ADMINS_UPDATE_FAILURE',

  GETBYID_REQUEST: 'ADMINS_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'ADMINS_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'ADMINS_GETBYID_FAILURE',
};
