services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: online_course
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: .
    image: online-course-backend:v1.0.0
    container_name: online-course-backend
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - APP_JWT_SECRET=${JWT_SECRET}
      - APP_JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ACCOUNT_1=${ACCOUNT_1}
      - ACCOUNT_1_ID=${ACCOUNT_1_ID}
      - ACCOUNT_2=${ACCOUNT_2}
      - ACCOUNT_2_ID=${ACCOUNT_2_ID}
      - ACCOUNT_3=${ACCOUNT_3}
      - ACCOUNT_3_ID=${ACCOUNT_3_ID}
      - ACCOUNT_4=${ACCOUNT_4}
      - ACCOUNT_4_ID=${ACCOUNT_4_ID}
      - ACCOUNT_5=${ACCOUNT_5}
      - ACCOUNT_5_ID=${ACCOUNT_5_ID}
    volumes:
      - /var/www/html/online-course/uploads:/app/uploads
    depends_on:
      - db-mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
