FROM eclipse-temurin:17-jdk-alpine

# Đặt thư mục làm việc
WORKDIR /app/online-course

# Sao chép file JAR từ target vào container
COPY target/online-course-0.0.1-SNAPSHOT.jar app.jar

# Tạo thư mục uploads (nếu cần cho upload file)
RUN mkdir -p /app/online-course/uploads

# Mở cổng 8080 cho ứng dụng Spring Boot
EXPOSE 8080

# Lệnh khởi động ứng dụng
ENTRYPOINT ["java", "-jar", "app.jar"]