version: "3.8"

services:
  backend:
    build: .
    image: online-course-backend:latest
    container_name: online-course-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - /var/www/uploads:/app/uploads
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
